all:
	gcc Matchup.c LogisticEmbed_common.c EmbedIO.c GamePairHash.c SparseVec.c NeuralLayer.c -lm -O3 -o ../bin/Matchup

debug:
	gcc Matchup.c LogisticEmbed_common.c EmbedIO.c GamePairHash.c SparseVec.c NeuralLayer.c -lm -g -o ../bin/Matchup

clean:
	rm -f ../bin/Matchup
